# Generated by Django 5.1.dev20240130101038 on 2024-02-24 14:12

from django.db import migrations, models

def populate_items(apps, schema_editor):
    Item = apps.get_model('users', 'Item')
    Item.objects.create(item_name="binhatitem", item_description="Hat straight from a bin!", item_cost=100)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(max_length=400)),
                ('item_cost', models.IntegerField(default=100)),
            ],
        ),
        migrations.RunPython(populate_items),
    ]
