# Generated by Django 5.1.dev20240130101038 on 2024-02-25 18:06

from django.db import migrations

def populate_items(apps, schema_editor):
    Item = apps.get_model('users', 'Item')
    Item.objects.create(item_name="binhatitem.png", item_description="Hat straight from a bin!", item_cost=300)
    Item.objects.create(item_name="glassesitem.png", item_description="For those who can't see straight!", item_cost=200)
    Item.objects.create(item_name="goldmedalitem.png", item_description="A gold medal for coming first place!", item_cost=500)
    Item.objects.create(item_name="rubiishpickeritem.png", item_description="Get litter picking for pesky peoples litter!", item_cost=100)
    Item.objects.create(item_name="waterbottleitem.png", item_description="It's a water bottle!", item_cost=50)

class Migration(migrations.Migration):


    dependencies = [
        ('users', '0003_auto_20240224_1412'),
    ]

    operations = [
        migrations.RunPython(populate_items),
    ]
