# Generated by Django 5.0.3 on 2024-03-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_group_members_groupuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetail",
            name="buddy_happiness",
            field=models.FloatField(default=1),
        ),
    ]
