# Generated by Django 5.0.1 on 2024-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240224_1412'),
        ('users', '0004_alter_friend_unique_together'),
    ]

    operations = [
    ]
