# Generated by Django 5.1.dev20240130101038 on 2024-02-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friend_unique_together'),
        ('users', '0004_auto_20240225_1806'),
    ]

    operations = [
    ]
