# Generated by Django 5.0.2 on 2024-02-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20240225_1732'),
        ('users', '0005_merge_20240225_1817'),
    ]

    operations = [
    ]
