# Generated by Django 5.0.3 on 2024-03-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userdetail_last_happiness_decay_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="last_happiness_decay_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
