# Generated by Django 4.2.10 on 2024-02-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_merge_20240225_1732"),
        ("users", "0005_merge_20240225_1817"),
    ]

    operations = []
