# Generated by Django 5.0.3 on 2024-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userdetail_last_happiness_decay_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="buddy_happiness",
            field=models.FloatField(default=0.75),
        ),
    ]
