# Generated by Django 5.0.3 on 2024-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_userdetail_buddy_happiness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="buddy_name",
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="buddy_type",
            field=models.CharField(max_length=50),
        ),
    ]
