# Generated by Django 4.2.10 on 2024-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TaskName", models.CharField(max_length=200)),
                ("Description", models.CharField(max_length=400)),
                ("DifficultyLevel", models.CharField(max_length=10)),
                ("CoinReward", models.IntegerField(default=0)),
                ("XpReward", models.IntegerField(default=0)),
            ],
        ),
    ]
