# Generated by Django 4.2.6 on 2024-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="GeoLat",
            field=models.FloatField(default=50.737489464168995),
        ),
        migrations.AddField(
            model_name="task",
            name="GeoLong",
            field=models.FloatField(default=-3.5344444340166734),
        ),
    ]
