# Generated by Django 5.0.1 on 2024-03-18 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_grouptask'),
        ('users', '0007_alter_userdetail_buddy_happiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouptask',
            unique_together={('group', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='usertask',
            unique_together={('user_id', 'task_id')},
        ),
    ]
