# Generated by Django 5.0.3 on 2024-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_qrdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="GeoRange",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="task",
            name="QrData",
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="TaskName",
            field=models.CharField(max_length=50),
        ),
    ]
