# Generated by Django 5.0.1 on 2024-02-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usertask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='TaskID',
            new_name='task_id',
        ),
    ]
