# Generated by Django 5.0.1 on 2024-02-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_taskid_usertask_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='task_id',
            new_name='task',
        ),
    ]
