# Generated by Django 5.0.1 on 2024-02-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_task_id_usertask_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
