# Generated by Django 5.0.2 on 2024-02-26 13:55

from django.db import migrations


def populate_items(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    Item.objects.create(item_name="Bin Hat", item_location="binhatitem.png", item_description="Hat straight from a bin!", item_cost=300)
    Item.objects.create(item_name="Glasses", item_location="glassesitem.png", item_description="For those who can't see straight!", item_cost=200)
    Item.objects.create(item_name="Gold Medal", item_location="goldmedalitem.png", item_description="A gold medal for coming first place!", item_cost=500)
    Item.objects.create(item_name="Rubish Picker", item_location="rubiishpickeritem.png", item_description="Get litter picking for pesky peoples litter!", item_cost=100)
    Item.objects.create(item_name="Water Bottle", item_location="waterbottleitem.png", item_description="It's a water bottle!", item_cost=50)

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_items),
    ]