# Generated by Django 5.0.2 on 2024-02-26 16:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_userbitems_useritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together={('user', 'item')},
        ),
    ]
